#' @title Two-Accumulator Linear Ballistic Accumulator (LBA) Model
#'
#' @description
#' The Linear Ballistic Accumulator (LBA) treats a choice as a race between two
#' accumulators that rise **linearly** - no within-trial noise at all - each at a
#' rate drawn afresh on every trial. The first to reach the threshold determines
#' both the reaction time and the choice. The observed RT is that decision time
#' shifted by a non-decision time `ndt`, and a fixed proportion `poutlier` of
#' responses is generated by an outlier process instead of by the race.
#'
#' Functions:
#' - `rcogmod_lba2()`: Simulates random draws from the LBA.
#' - `dcogmod_lba2()`: Computes the density (likelihood).
#' - `cogmod_lba2()`: Creates a `brms::custom_family()` for use in `brms` models.
#' - `cogmod_lba2_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#' - `p_outlier()`: Per-trial posterior probability of being an outlier.
#'
#' @details
#' # Parameterization
#'
#' Accumulator `k` starts at a point `z ~ Uniform(0, sigmabias)`, drawn afresh on
#' every trial, and rises at a constant rate `v ~ Normal(drift_k, sigma_k)`, also
#' drawn afresh on every trial, until it reaches the threshold
#' `b = boundary + sigmabias`. Its finishing time is therefore `(b - z) / v`, and
#' `boundary` is the threshold *offset*: the distance from the highest possible
#' starting point to the threshold. All the randomness is between trials; within
#' a trial the path is a straight line, which is what makes the density
#' closed-form.
#'
#' This is the `B` parameterization of `DMC` and `EMC2`, where `b = B + A` with
#' `A` the start-point range. It is used for a reason rather than for taste: the
#' threshold has to sit above the highest possible starting point, and writing
#' the *offset* makes `b > A` hold automatically for any positive value. The
#' alternative - estimating the absolute threshold, as `rtdists` does - needs an
#' order constraint between two estimated parameters, which has to hold in every
#' cell of the design once either of them carries a predictor. The cost is that
#' `boundary` alone is not the quantity to read off a fitted model; `boundary +
#' sigmabias` is.
#'
#' `ndt` is expressed **directly, in seconds** (through a log link in the `brms`
#' family). Nothing about it is taken from the data: it is not bounded by the
#' fastest observed response, so a non-decision time that varies by condition or
#' by participant can exceed the sample minimum wherever the data support it.
#'
#' This replaces the earlier `tau` / `minrt` pair, in which `ndt = tau * minrt`
#' with `minrt` set to the fastest observed RT. That capped the non-decision
#' time at an order statistic of the sample, so any condition or participant
#' whose true `ndt` exceeded the fastest observed response was inexpressible,
#' and the misfit surfaced as spurious effects on the race parameters.
#'
#' # Negative drift rates
#'
#' A normal drift rate can come out negative, and such an accumulator rises
#' away from the threshold and never responds. A trial on which *both* drifts
#' are negative produces no response at all, so it is not a trial: the process
#' is conditioned on at least one of the two being positive, and
#' `rcogmod_lba2()` draws from exactly that conditional distribution.
#'
#' The density is conditioned to match, dividing by
#' `1 - pnorm(-driftzero / sigmazero) * pnorm(-driftone / sigmaone)`. Without
#' that factor the density integrates to the probability of the event rather
#' than to one, which at low drift rates is a long way short - `0.83` at drifts
#' of `0.5` and `0.2` with SDs of `1.5`, so the likelihood is wrong by 17% and
#' wrong by *different* amounts at different parameter values, which is what
#' makes it bias estimates rather than merely offset them.
#'
#' # The evidence scale is arbitrary
#'
#' Multiply `driftzero`, `driftone`, `sigmazero`, `sigmaone`, `sigmabias` and
#' `boundary` all by any `c > 0` and every finishing time `(b - z) / v` is
#' unchanged. The likelihood is therefore **exactly** constant along that ray,
#' which runs to infinity in both directions: the six parameters are identified
#' only up to a common scale factor.
#'
#' [cogmod_priors()] puts priors on all four positive parameters, which makes
#' the posterior proper and the sampler well behaved, but a prior does not
#' *identify* a direction the likelihood cannot see. If the individual
#' parameters are to be interpreted - rather than the RT distribution they
#' jointly generate, which is perfectly well identified - fix one SD in the
#' formula, the usual convention being `sigmazero = 1`:
#'
#' ```r
#' f <- brms::bf(RT | dec(Error) ~ Condition, driftone ~ Condition,
#'               sigmazero = 1, sigmaone ~ 1, sigmabias ~ 1, boundary ~ 1,
#'               ndt ~ 1, poutlier ~ 1, family = cogmod_lba2())
#' ```
#'
#' A second, milder flat direction remains either way: `sigmabias` and
#' `boundary` enter only through the sum `b = boundary + sigmabias`, so they
#' trade off along a ridge. The sum is the trustworthy quantity to interpret and
#' to compare across conditions. [cogmod_lba1()] and [cogmod_rdm()] share it.
#'
#' # The outlier component
#'
#' A shifted distribution assigns exactly zero density to any response faster
#' than `ndt`, which puts a hard boundary in the likelihood at the fastest
#' observed RT. Mixing in a component with support over the whole positive line
#' removes it: every response keeps positive density whatever `ndt` is, so the
#' boundary becomes a finite cost rather than a wall and the log-density stays
#' smooth and differentiable.
#'
#' Because this model produces a **choice as well as a time**, the contaminant
#' has to produce both. It is a guess: the choice is uniform over the two
#' options, and the RT is a **half Normal** with scale `0.2` seconds.
#'
#' \deqn{f(t, k) = p \frac{1}{K} g(t) + (1 - p) f_k(t - ndt)}
#'
#' The `1 / K` is what keeps the total summing to one over the response options;
#' without it it would come to `1 + poutlier`.
#'
#' `poutlier` is a *rate*, not a classification: the model never labels
#' individual trials, it estimates what share of them came from elsewhere. Use
#' [p_outlier()] for per-trial posterior probabilities.
#'
#' # Reaction times must be in seconds
#'
#' The outlier component's scale is a constant in seconds, and so are the
#' priors [cogmod_priors()] supplies. There is no argument for changing the
#' unit: the `minrt` argument that used to rescale the component was removed in
#' 0.2.1. Millisecond data fails silently rather than loudly - the outlier
#' component contributes nothing and the min-RT boundary comes back. See the
#' corresponding section of [cogmod_lognormal()] for the full account, which
#' applies unchanged here.
#'
#' # Fitting
#'
#' ```r
#' f <- brms::bf(RT | dec(Error) ~ Condition, driftone ~ Condition,
#'               sigmazero = 1, sigmaone ~ 1, sigmabias ~ 1, boundary ~ 1,
#'               ndt ~ 1, poutlier ~ 1, family = cogmod_lba2())
#' brms::brm(f, data = df,
#'           prior    = cogmod_priors(f, df),
#'           init     = cogmod_inits(f, df),
#'           stanvars = cogmod_stanvars(f))
#' ```
#'
#' The `brms` family names the drift of the first accumulator `mu` (as `brms`
#' requires) and that of the second `driftone`. Use [cogmod_inits()] rather than
#' `init = 0`: `brms` initialises on the unconstrained scale, so `init = 0` puts
#' `ndt` at `exp(0) = 1` second - above nearly every sub-second RT, which leaves
#' every response attributed to the outlier component and the race parameters
#' with no gradient at all.
#'
#' # Predictions exclude the outlier component
#'
#' `posterior_predict()` describes the **race alone** by default, as if
#' `poutlier` were zero, because the outlier component is a fixed regularizer
#' rather than a claim about how guesses are distributed. Use [with_outliers()]
#' for the fitted mixture - chiefly for `brms::pp_check()` - and
#' [without_outliers()] to go back. `log_lik()` is always the full mixture.
#'
#' `posterior_epred()` is not provided: for a race model the expectation needs
#' numerical integration per draw and per observation, and users are better off
#' summarising `posterior_predict()` draws.
#'
#' @param n Number of simulated trials. If `length(n) > 1`, the length is taken
#'   to be the number required.
#' @param driftzero,driftone Mean drift rate of each accumulator (choice 0 and
#'   1). Any real value; larger means faster. See Details on negative drifts.
#' @param sigmazero,sigmaone Between-trial SD of each accumulator's drift rate.
#'   Must be positive.
#' @param sigmabias Maximum starting point. The starting point of each
#'   accumulator on each trial is drawn from `Uniform(0, sigmabias)`. Must be
#'   non-negative; `0` means both accumulators start at zero on every trial, so
#'   only the drift rates vary - the choice counterpart of the recinormal
#'   special case described in [rcogmod_lba1()].
#' @param boundary Threshold offset, so the threshold is
#'   `b = boundary + sigmabias`. Must be positive.
#' @param ndt Non-decision time (shift parameter), in seconds. Represents the
#'   time taken for processes unrelated to the decision (e.g., encoding, motor
#'   response). Must be non-negative. Range: `[0, Inf)`.
#' @param poutlier Proportion of responses generated by the outlier process
#'   rather than by the race. Range: `[0, 1]`. At `poutlier = 0` the
#'   distribution reduces to the plain shifted LBA.
#'
#' @return `rcogmod_lba2()` returns a data frame with `n` rows and two columns:
#'   \item{rt}{The simulated reaction time.}
#'   \item{response}{The winning accumulator, coded `0` or `1`, matching the
#'     `dec()` coding used by the `brms` families.}
#'
#'   `dcogmod_lba2()` returns the defective density at each element of `x` -
#'   the log density if `log = TRUE` - for the response given in `response`,
#'   recycled to the length of the longest argument. `cogmod_lba2()` returns a
#'   `brms::custom_family` object, to put on a `brms::bf()` formula.
#'   `cogmod_lba2_stanvars()` returns a `brms::stanvars` object holding the
#'   family's Stan `functions` block, to pass to `brms::brm()`, and
#'   `cogmod_lba2_lpdf_expose()` compiles that Stan code and returns it as an R
#'   function, for checking the density outside of a model. The remaining
#'   functions are `brms` post-processing methods, called by `brms` rather than
#'   directly: `log_lik_cogmod_lba2()` returns a numeric vector holding one
#'   log-likelihood value per posterior draw for observation `i`, and
#'   `posterior_predict_cogmod_lba2()` a draws x 2 matrix of reaction times and
#'   choices simulated for observation `i`.
#'   `posterior_epred_cogmod_lba2()` returns nothing: the expected reaction
#'   time of a race has no closed form, so it errors rather than report one -
#'   summarise `posterior_predict()` draws instead.
#'
#' @references
#' - Brown, S. D., & Heathcote, A. (2008). The simplest complete model of choice response time:
#'     Linear ballistic accumulation. *Cognitive Psychology*, *57*(3), 153-178.
#'     \doi{10.1016/j.cogpsych.2007.12.002}
#'
#' @seealso [rcogmod_lba1()], [rcogmod_rdm()], [rcogmod_lnr()]
#'
#' @examples
#' # Simulate data, with 2% of trials from the outlier process
#' data <- rcogmod_lba2(1000,
#'   driftzero = 3, driftone = 2, sigmazero = 1, sigmaone = 1,
#'   sigmabias = 0.5, boundary = 0.5, ndt = 0.2, poutlier = 0.02
#' )
#' head(data)
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_lba2(0.1, ndt = 0.2, response = 0, poutlier = 0.02)
#' dcogmod_lba2(0.1, ndt = 0.2, response = 0, poutlier = 0)
#'
#' @export
rcogmod_lba2 <- function(n, driftzero = 3, driftone = 3, sigmazero = 1,
                         sigmaone = 1, sigmabias = 0.5, boundary = 0.5,
                         ndt = 0.2, poutlier = 0) {
  .rchoice("cogmod_lba2", n = n, ndt = ndt, poutlier = poutlier, mu = driftzero, driftone = driftone, sigmazero = sigmazero,
           sigmaone = sigmaone, sigmabias = sigmabias, boundary = boundary)
}


#' @rdname rcogmod_lba2
#' @param x The observed reaction time (RT).
#' @param response The winning accumulator (0 or 1). This gives the *defective*
#'   density `f_response(x) * S_other(x)`, mixed with the outlier component,
#'   which is what a race likelihood needs.
#' @param log Logical; if TRUE, returns the log-density. Default: FALSE.
#' @export
dcogmod_lba2 <- function(x, driftzero = 3, driftone = 3, sigmazero = 1,
                         sigmaone = 1, sigmabias = 0.5, boundary = 0.5,
                         ndt = 0.2, response, poutlier = 0, log = FALSE) {
  .dchoice("cogmod_lba2", x = x, response = response, ndt = ndt,
           poutlier = poutlier, log = log,
           mu = driftzero, driftone = driftone, sigmazero = sigmazero,
           sigmaone = sigmaone, sigmabias = sigmabias, boundary = boundary)
}


# Family ------------------------------------------------------------------

#' @rdname rcogmod_lba2
#' @param link_mu,link_driftone Link functions for the two mean drift rates.
#'   `mu` is `driftzero`: `brms` requires the first distributional parameter of
#'   a custom family to be called `mu`.
#' @param link_sigmazero,link_sigmaone Link functions for the between-trial
#'   drift SDs.
#' @param link_sigmabias,link_boundary Link functions for the start-point range
#'   and the threshold offset.
#' @param link_ndt,link_poutlier Link functions for the non-decision time and
#'   the outlier rate.
#' @param predict_outliers Logical; whether `posterior_predict()` should include
#'   the outlier component. `FALSE` (the default) fixes `poutlier` to zero for
#'   prediction, so predictions describe the race alone; the likelihood is
#'   always the full mixture either way. On the prediction method itself the
#'   default is `NULL`, which defers to the flag carried on the model - see
#'   [with_outliers()] to change it after fitting. See Details.
#' @export
cogmod_lba2 <- function(
  link_mu = "identity",
  link_driftone = "identity",
  link_sigmazero = "softplus",
  link_sigmaone = "softplus",
  link_sigmabias = "softplus",
  link_boundary = "softplus",
  link_ndt = "log",
  link_poutlier = "logit",
  predict_outliers = FALSE
) {
  .choice_family(
    "cogmod_lba2",
    links = c(link_mu, link_driftone, link_sigmazero, link_sigmaone,
              link_sigmabias, link_boundary),
    predict_outliers = predict_outliers
  )
}


# The decision component, as the registry wants it ------------------------

# Log-density of the race at decision time `t` (already net of the non-decision
# time) for the accumulator named by `k`: that accumulator's defective density
# times the other one's survival, divided by the probability that at least one
# drift is positive - the event the process is conditioned on.
#
# `.ldec_choice()` masks out `t <= 0` and restores the shape afterwards, so this
# only has to work elementwise. Everything is flattened first because
# `p_outlier()` passes draws x observations matrices.
#' @keywords internal
.lba2_ldens <- function(t, k, p) {
  v_win <- as.vector(ifelse(k == 0, p$mu, p$driftone))
  s_win <- as.vector(ifelse(k == 0, p$sigmazero, p$sigmaone))
  v_los <- as.vector(ifelse(k == 0, p$driftone, p$mu))
  s_los <- as.vector(ifelse(k == 0, p$sigmaone, p$sigmazero))
  tv <- as.vector(t)
  aa <- as.vector(p$sigmabias)
  bb <- as.vector(p$boundary)

  # The 1e-10 floor only keeps sigma * t away from an exact zero; z1 then runs
  # off to +/-Inf, which the density and survival both handle.
  stw <- pmax(s_win * tv, 1e-10)
  f <- .lba_dens_over_A(v_win, s_win, stw, (bb - v_win * tv) / stw, aa / stw)
  stl <- pmax(s_los * tv, 1e-10)
  surv <- .lba_surv_raw(v_los, s_los, stl, (bb - v_los * tv) / stl, aa / stl)

  # log P(both drifts negative). At -Inf (the ordinary case) log1m_exp is 0 and
  # the normalisation costs nothing; at 0 the model says neither accumulator
  # ever responds, so the observed response is impossible.
  lq <- stats::pnorm(-v_win / s_win, log.p = TRUE) +
    stats::pnorm(-v_los / s_los, log.p = TRUE)

  ok <- f > 0 & surv > 0 & lq < 0
  out <- rep(-Inf, length(tv))
  if (any(ok)) {
    out[ok] <- log(f[ok]) + log(surv[ok]) - .log1m_exp(lq[ok])
  }
  out
}


# Decision-component sampler. Both drifts and both start points are drawn afresh
# per trial, conditioned on at least one drift being positive.
#
# That condition is imposed exactly rather than by rejection. Writing
# `q_k = P(v_k <= 0)`, the conditional law splits into two disjoint cases:
# accumulator 0 positive (probability `(1 - q0) / (1 - q0 q1)`), with
# accumulator 1 unconstrained; or accumulator 0 non-positive and accumulator 1
# positive. Sampling the case first and then the truncated normals reproduces
# the conditional joint distribution with no loop to bound - and so no
# `max_iter` argument, and no fallback that quietly draws from the wrong
# distribution when the loop runs out.
#' @keywords internal
.lba2_rng <- function(n, p) {
  lq0 <- stats::pnorm(-p$mu / p$sigmazero, log.p = TRUE)
  lq1 <- stats::pnorm(-p$driftone / p$sigmaone, log.p = TRUE)
  # P(at least one positive drift), via expm1 so that it stays accurate when
  # both accumulators are near-certain to fail.
  denom <- -expm1(lq0 + lq1)
  first <- stats::runif(n) < stats::pnorm(p$mu / p$sigmazero) / denom

  v0 <- numeric(n)
  v1 <- numeric(n)
  if (any(first)) {
    i <- which(first)
    v0[i] <- .rnorm_truncated(length(i), p$mu[i], p$sigmazero[i], lower = 0)
    v1[i] <- stats::rnorm(length(i), p$driftone[i], p$sigmaone[i])
  }
  if (any(!first)) {
    i <- which(!first)
    v0[i] <- .rnorm_truncated(length(i), p$mu[i], p$sigmazero[i], upper = 0)
    v1[i] <- .rnorm_truncated(length(i), p$driftone[i], p$sigmaone[i],
                              lower = 0)
  }

  b <- p$sigmabias + p$boundary
  z0 <- stats::runif(n, min = 0, max = p$sigmabias)
  z1 <- stats::runif(n, min = 0, max = p$sigmabias)
  # A non-positive drift rises away from the threshold and never gets there.
  t0 <- ifelse(v0 > 0, (b - z0) / v0, Inf)
  t1 <- ifelse(v1 > 0, (b - z1) / v1, Inf)

  list(rt = pmin(t0, t1), response = as.numeric(t0 >= t1))
}


# Stanvars ----------------------------------------------------------------

# The two kernels are shared with cogmod_lba1() (see .LBA_STAN_PRELUDE in
# core_shifted.R); only the race on top of them is specific to this family.
#' @keywords internal
.LBA2_STAN_PRELUDE <- paste0(
  .LBA_STAN_PRELUDE,
  "
// Defective log-density of one LBA race outcome at decision time t: the winner
// reaching the threshold just then, while the loser has not reached it at all.
//
// The subtraction is the conditioning: a trial on which both drifts came out
// negative produces no response, so it is not a trial, and the density has to
// be divided by the probability that at least one of them is positive. Without
// it the density integrates to that probability rather than to one.
real cogmod_lba2_decision_lpdf(real t, real v_win, real s_win,
                               real v_los, real s_los,
                               real sigmabias, real boundary) {
  real stw = fmax(s_win * t, 1e-10);
  real z1w = (boundary - v_win * t) / stw;
  real f = cogmod_lba_dens_over_A(v_win, s_win, stw, z1w, sigmabias / stw);
  if (f <= 0) return negative_infinity();

  real stl = fmax(s_los * t, 1e-10);
  real z1l = (boundary - v_los * t) / stl;
  real surv = cogmod_lba_surv(z1l, sigmabias / stl);
  if (surv <= 0) return negative_infinity();

  real lq = std_normal_lcdf(-v_win / s_win) + std_normal_lcdf(-v_los / s_los);
  if (lq >= 0) return negative_infinity();

  return log(f) + log(surv) - log1m_exp(lq);
}
"
)


#' @keywords internal
.cogmod_lba2_lpdf <- function() {
  .choice_lpdf("cogmod_lba2")
}


#' @rdname rcogmod_lba2
#' @examples
#' \donttest{
#' # Exposing the Stan function needs cmdstanr and a CmdStan toolchain,
#' # which live outside CRAN - see the package website to install them.
#' if (requireNamespace("cmdstanr", quietly = TRUE) &&
#'     !is.null(cmdstanr::cmdstan_version(error_on_NA = FALSE))) {
#'   lpdf <- cogmod_lba2_lpdf_expose()
#'   lpdf(
#'     Y = 0.5, mu = 3, driftone = 2, sigmazero = 1, sigmaone = 1,
#'     sigmabias = 0.5, boundary = 0.5, ndt = 0.2, poutlier = 0.02, dec = 0
#'   )
#' }
#' }
#'
#' @export
cogmod_lba2_lpdf_expose <- function() {
  .choice_expose("cogmod_lba2")
}


#' @rdname rcogmod_lba2
#' @export
cogmod_lba2_stanvars <- function() {
  brms::stanvar(
    scode = .cogmod_lba2_lpdf(),
    block = "functions"
  )
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_lba2
#' @inheritParams rcogmod_betagate
#' @export
log_lik_cogmod_lba2 <- function(i, prep) {
  .log_lik_choice("cogmod_lba2", i, prep)
}


#' @rdname rcogmod_lba2
#' @inheritParams rcogmod_betagate
#' @importFrom brms get_dpar
#' @export
posterior_predict_cogmod_lba2 <- function(i, prep, predict_outliers = NULL,
                                          ...) {
  .posterior_predict_choice("cogmod_lba2", i, prep, predict_outliers)
}


#' @rdname rcogmod_lba2
#' @export
posterior_epred_cogmod_lba2 <- function(prep) {
  stop(
    "Computing posterior_epred for a race model needs numerical integration ",
    "per draw and per observation, which is prohibitive here. Use ",
    "posterior_predict() and summarise the draws instead.",
    call. = FALSE
  )
}
