#' @title Drift Diffusion Model (DDM)
#'
#' @description
#' The Drift Diffusion Model (DDM) describes a two-choice decision as noisy
#' evidence accumulating between two boundaries until one of them is reached.
#' The boundary reached is the choice and the time taken is the decision time.
#' The observed RT is that decision time shifted by a non-decision time `ndt`,
#' and a fixed proportion `poutlier` of responses is generated by an outlier
#' process instead of by the diffusion.
#'
#' Functions:
#' - `rcogmod_ddm()`: Simulates random draws from the DDM.
#' - `dcogmod_ddm()`: Computes the density (likelihood).
#' - `pcogmod_ddm()`: Computes the cumulative distribution function.
#' - `cogmod_ddm()`: Creates a `brms::custom_family()` for use in `brms` models.
#' - `cogmod_ddm_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#' - `p_outlier()`: Per-trial posterior probability of being an outlier.
#'
#' @details
#' # Response coding
#'
#' The response coded `1` (`response` here, `dec()` in a `brms` formula) is the
#' **upper** boundary and the response coded `0` is the **lower** one, following
#' `brms`'s own `wiener()` family. Two consequences are worth keeping in mind
#' when reading a fitted model:
#'
#' * `bias` is measured *from the lower boundary*, so `bias > 0.5` places the
#'   starting point closer to the response coded `1`, and `bias < 0.5` closer to
#'   the response coded `0`. Since first-passage times are shorter for the nearer
#'   boundary, `bias > 0.5` makes responses coded `1` *faster* than responses
#'   coded `0`, and `bias < 0.5` makes them slower. At exactly `bias = 0.5` the
#'   two conditional RT distributions are identical, whatever the drift rate.
#' * A positive `drift` pushes the accumulator towards the response coded `1`.
#'   When `0` codes correct responses and `1` codes errors (a common choice when
#'   the task has no natural stimulus-to-boundary mapping), good performance
#'   therefore corresponds to a *negative* drift rate.
#'
#' # Parameterization
#'
#' `ndt` is expressed **directly, in seconds** (through a log link in the `brms`
#' family). Nothing about it is taken from the data: it is not bounded by the
#' fastest observed response, so a non-decision time that varies by condition or
#' by participant can exceed the sample minimum wherever the data support it.
#'
#' This replaces the earlier `tau` / `minrt` pair, in which `ndt = tau * minrt`
#' with `minrt` set to the fastest observed RT. That capped the non-decision
#' time at an order statistic of the sample, so any condition or participant
#' whose true `ndt` exceeded the fastest observed response was inexpressible,
#' and the misfit surfaced as spurious effects on the other parameters.
#'
#' `sigmatau` went with it, and is now **`sigmandt`**. It is the between-trial
#' *range* of the non-decision time (`st0` in the usual notation), expressed
#' directly in the same unit as the data rather than as a fraction of `minrt`,
#' with `ndt` the lower bound of the resulting Uniform. The old name was a
#' compound of a parameter that no longer exists and a scale factor the user no
#' longer sees.
#'
#' # Between-trial variability
#'
#' `sigmadrift`, `sigmabias` and `sigmandt` extend the classic 4-parameter
#' process to the full 7-parameter one. Each is legitimately **zero**, and
#' setting all three to zero in the formula recovers the classic model:
#'
#' ```r
#' brms::bf(RT | dec(Error) ~ Condition, sigmadrift = 0, sigmabias = 0,
#'          sigmandt = 0, ndt ~ 1, poutlier ~ 1, family = cogmod_ddm())
#' ```
#'
#' Writing `sigmadrift = 0` **fixes** the parameter; leaving it out of `bf()`
#' altogether *estimates* it, which is not the same thing. All three are hard to
#' recover even from a lot of data, and each has a flat direction at its own
#' floor - the link only reaches zero at minus infinity, and the likelihood stops
#' changing well before then - so [cogmod_priors()] gives all three deliberately
#' tight priors. Fixing the ones a design cannot identify is usually better than
#' estimating them behind a prior.
#'
#' # The outlier component
#'
#' A shifted distribution assigns exactly zero density to any response faster
#' than `ndt`, which puts a hard boundary in the likelihood at the fastest
#' observed RT. Mixing in a component with support over the whole positive line
#' removes it: every response keeps positive density whatever `ndt` is, so the
#' boundary becomes a finite cost rather than a wall and the log-density stays
#' smooth and differentiable.
#'
#' Because this model produces a **choice as well as a time**, the contaminant
#' has to produce both. It is a guess: the choice is uniform over the two
#' options, and the RT is a **half Normal** with scale `0.2` seconds.
#'
#' \deqn{f(t, k) = p \frac{1}{K} g(t) + (1 - p) f_k(t - ndt)}
#'
#' The `1 / K` is what keeps the total summing to one over the response options;
#' without it it would come to `1 + poutlier`.
#'
#' `poutlier` is a *rate*, not a classification: the model never labels
#' individual trials, it estimates what share of them came from elsewhere. Use
#' [p_outlier()] for per-trial posterior probabilities.
#'
#' # Reaction times must be in seconds
#'
#' The outlier component's scale is a constant in seconds, and so are the
#' priors [cogmod_priors()] supplies. There is no argument for changing the
#' unit: the `minrt` argument that used to rescale the component was removed in
#' 0.2.1. Millisecond data fails silently rather than loudly - the outlier
#' component contributes nothing and the min-RT boundary comes back. See the
#' corresponding section of [cogmod_lognormal()] for the full account, which
#' applies unchanged here.
#'
#' # Implementation
#'
#' The 4-parameter density is [brms::dwiener()] (which requires the `RWiener`
#' package). Draws are taken by inverting the first-passage CDF, which - unlike
#' [brms::rwiener()], and unlike `rtdists` - vectorises over parameter sets, so
#' the per-call setup is paid once rather than once per posterior draw. That
#' matters for [posterior_predict()], where every draw carries its own
#' parameters; it is several times faster there and agrees with both packages'
#' samplers to within sampling error.
#'
#' The full 7-parameter model is built on top of these rather than delegated to
#' another package: between-trial variability is simulated by drawing the
#' per-trial parameters, and evaluated by combining a closed-form drift
#' correction with Gauss-Legendre quadrature over the starting point and
#' non-decision time.
#'
#' In Stan the decision component is `wiener_lpdf()`, called with its own
#' non-decision time set to zero because the shift is applied by the mixture
#' around it, and short-circuited to the cheaper 4- and 5-parameter forms
#' whenever the start-point and non-decision-time ranges both vanish. The
#' cheapest of the three, Stan's classic 4-parameter density, is used only where
#' it is sound: it returns `-inf` with **NaN** derivatives once the rescaled
#' decision time `t / boundary^2` falls below about `6.6e-4`, or once the density
#' underflows, and a NaN derivative on a trial the mixture gives no weight to
#' still turns the gradient of the whole model to NaN. Those calls go to the
#' `sv`-capable form instead, which the two agree with to `1e-13` where they
#' meet.
#'
#' # Fitting
#'
#' ```r
#' f <- brms::bf(RT | dec(Error) ~ Condition, boundary ~ Condition, bias ~ 1,
#'               sigmadrift = 0, sigmabias = 0, sigmandt = 0,
#'               ndt ~ 1, poutlier ~ 1, family = cogmod_ddm())
#' brms::brm(f, data = df,
#'           prior    = cogmod_priors(f, df),
#'           init     = cogmod_inits(f, df),
#'           stanvars = cogmod_stanvars(f))
#' ```
#'
#' Use [cogmod_inits()] rather than `init = 0`. `brms` initialises on the
#' unconstrained scale, so `init = 0` puts `ndt` at `exp(0) = 1` second - above
#' nearly every sub-second RT, which leaves every response attributed to the
#' outlier component and the diffusion parameters with no gradient at all.
#'
#' # Predictions exclude the outlier component
#'
#' `posterior_predict()` and `posterior_epred()` describe the **diffusion
#' alone** by default, as if `poutlier` were zero, because the outlier component
#' is a fixed regularizer rather than a claim about how guesses are distributed.
#' Use [with_outliers()] for the fitted mixture - chiefly for
#' `brms::pp_check()` - and [without_outliers()] to go back. `log_lik()` is
#' always the full mixture.
#'
#' @param n Number of simulated trials. If `length(n) > 1`, the length is taken
#'   to be the number required.
#' @param drift Drift rate. Any real value; positive pushes the accumulator
#'   towards the boundary coded `1`.
#' @param boundary Boundary separation. Must be positive.
#' @param bias Starting point, as a proportion of the boundary separation
#'   *measured from the boundary coded `0`*. Must be in `(0, 1)`.
#' @param ndt Non-decision time (shift parameter), in seconds. Must be
#'   non-negative. With `sigmandt > 0` it is the **lower bound** of the
#'   between-trial distribution rather than its midpoint.
#' @param sigmadrift Between-trial SD of the drift rate (`sv`). Must be
#'   non-negative. Default `0`.
#' @param sigmabias Between-trial start-point range, as a fraction in `[0, 1)`
#'   of the widest range that keeps the start point inside the boundaries:
#'   `sw = sigmabias * min(2 * bias, 2 * (1 - bias))`. Default `0`.
#' @param sigmandt Between-trial range of the non-decision time (`st0`), in the
#'   same unit as the data, with `ndt` its lower bound. Default `0`. Formerly
#'   `sigmatau`, which was a fraction of `minrt`.
#' @param poutlier Proportion of responses generated by the outlier process
#'   rather than by the diffusion. Range: `[0, 1]`.
#'
#' @return `rcogmod_ddm()` returns a data frame with `n` rows and two columns:
#'   \item{rt}{The simulated reaction time.}
#'   \item{response}{The boundary reached, `1` for upper and `0` for lower,
#'     matching the `dec()` coding used by the `brms` families.}
#'
#'   `dcogmod_ddm()` returns the defective density at each element of `x` - the
#'   log density if `log = TRUE` - and `pcogmod_ddm()` the defective cumulative
#'   probability at each element of `q`, both for the response given in
#'   `response` and recycled to the length of the longest argument.
#'   `cogmod_ddm()` returns a `brms::custom_family` object, to put on a
#'   `brms::bf()` formula. `cogmod_ddm_stanvars()` returns a `brms::stanvars`
#'   object holding the family's Stan `functions` block, to pass to
#'   `brms::brm()`, and `cogmod_ddm_lpdf_expose()` compiles that Stan code and
#'   returns it as an R function, for checking the density outside of a model.
#'   The remaining functions are `brms` post-processing methods, called by
#'   `brms` rather than directly: `log_lik_cogmod_ddm()` returns a numeric
#'   vector holding one log-likelihood value per posterior draw for observation
#'   `i`, `posterior_predict_cogmod_ddm()` a draws x 2 matrix of reaction times
#'   and choices simulated for observation `i`, and
#'   `posterior_epred_cogmod_ddm()` a draws x observations matrix of expected
#'   reaction times (marginal over the two responses, and only approximate once
#'   the between-trial variability parameters are non-zero).
#'
#' @references
#' - Ratcliff, R., & McKoon, G. (2008). The diffusion decision model: Theory and
#'     data for two-choice decision tasks. *Neural Computation*, *20*(4),
#'     873-922. \doi{10.1162/neco.2008.12-06-420}
#'
#' @seealso [rcogmod_rdm()], [rcogmod_lba2()], [rcogmod_lnr()]
#'
#' @examples
#' # Simulate data, with 2% of trials from the outlier process
#' data <- rcogmod_ddm(1000,
#'   drift = 0.5, boundary = 1, bias = 0.5, ndt = 0.2, poutlier = 0.02
#' )
#' head(data)
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_ddm(0.1, ndt = 0.2, response = 1, poutlier = 0.02)
#' dcogmod_ddm(0.1, ndt = 0.2, response = 1, poutlier = 0)
#'
#' @export
rcogmod_ddm <- function(n, drift = 0, boundary = 1, bias = 0.5, ndt = 0.2,
                        sigmadrift = 0, sigmabias = 0, sigmandt = 0,
                        poutlier = 0) {
  .rchoice("cogmod_ddm", n = n, ndt = ndt, poutlier = poutlier, mu = drift, boundary = boundary, bias = bias,
           sigmadrift = sigmadrift, sigmabias = sigmabias, sigmandt = sigmandt)
}


#' @rdname rcogmod_ddm
#' @param x The observed reaction time (RT).
#' @param response The boundary reached: `1` for the upper boundary, `0` for the
#'   lower one. This gives the *defective* density that boundary carries, mixed
#'   with the outlier component.
#' @param log Logical; if TRUE, returns the log-density. Default: FALSE.
#' @export
dcogmod_ddm <- function(x, drift = 0, boundary = 1, bias = 0.5, ndt = 0.2,
                        response, sigmadrift = 0, sigmabias = 0, sigmandt = 0,
                        poutlier = 0, log = FALSE) {
  .dchoice("cogmod_ddm", x = x, response = response, ndt = ndt,
           poutlier = poutlier, log = log,
           mu = drift, boundary = boundary, bias = bias,
           sigmadrift = sigmadrift, sigmabias = sigmabias, sigmandt = sigmandt)
}


#' @rdname rcogmod_ddm
#'
#' @description
#' `pcogmod_ddm()` is the cumulative distribution function: the probability that
#' a response has been made by time `q`. With `response = NULL` it is the RT
#' distribution marginally over the choice; with `response` set it is the
#' *defective* CDF that boundary carries, rising to the probability of that
#' boundary rather than to one.
#'
#' @details
#' # Accuracy of `pcogmod_ddm()`
#'
#' This CDF is more accurate than the one in `rtdists`, which is the usual
#' reference implementation. Deviation from numerical integration of the
#' density, at `drift = -4`, `boundary = 0.6`, `bias = 0.25`, by decision time:
#'
#' | decision time | this function | `rtdists::pdiffusion()` |
#' | --- | --- | --- |
#' | 0.02 | `+2.8e-16` | `+5.5e-04` |
#' | 0.05 | `-1.1e-16` | `+4.0e-04` |
#' | 0.30 | `-1.1e-16` | `+1.5e-04` |
#'
#' Over a grid of 360 (drift, boundary, bias, boundary-reached, time) cells the
#' worst deviation from integrating [dcogmod_ddm()] is 1e-15, i.e. rounding. The
#' choice probabilities are exact to the same order, where
#' `rtdists::pdiffusion(Inf, ...)` is out by up to 1.4e-04. The difference is
#' not academic: this function exists because [rcogmod_ddm()] inverts it to draw
#' from, so any error in it would land directly in the draws.
#'
#' `pcogmod_ddm()` covers the classic **4-parameter** DDM plus the outlier
#' component. The between-trial variability parameters would each need their own
#' quadrature layer on top - and `sigmadrift`, which the density handles with a
#' closed-form correction, has no such form here - so they are not arguments at
#' all: passing one is an error rather than a silently wrong number. Integrate
#' [dcogmod_ddm()] over `q` if you need them.
#'
#' With a `response`, `pcogmod_ddm()` returns the **defective** CDF
#' `P(RT <= q, choice = response)`, which does not reach one: its limit is the
#' probability of that boundary, given by `pcogmod_ddm(Inf, response = k)`. The
#' upper tail is then the matching defective survival
#' `P(RT > q, choice = response)`, so the two add to that response's own
#' probability rather than to one. Marginally (`response = NULL`) they add to
#' one as usual. [pcogmod_rdm()] follows the same convention.
#'
#' @param q Vector of quantiles (reaction times, in seconds).
#' @param lower.tail Logical; if TRUE (default) the probability is
#'   `P(RT <= q)`, otherwise `P(RT > q)`. With a `response`, both are defective
#'   - see Details.
#' @param log.p Logical; if TRUE, probabilities are returned on the log scale.
#' @export
pcogmod_ddm <- function(q, drift = 0, boundary = 1, bias = 0.5, ndt = 0.2,
                        response = NULL, poutlier = 0,
                        lower.tail = TRUE, log.p = FALSE) {
  # `response` is optional here but required by the shared preparation, so a
  # placeholder goes in when the marginal is wanted and is never read.
  params <- .prepare_choice("cogmod_ddm", x = q,
                            response = if (is.null(response)) 0 else response,
                            ndt = ndt, poutlier = poutlier,
                            mu = drift, boundary = boundary, bias = bias,
                            sigmadrift = 0, sigmabias = 0, sigmandt = 0)

  t_adj <- params$x - params$ndt
  # Response 1 is the upper boundary and `bias` is measured from the lower one,
  # following brms::wiener(). The upper boundary is the lower boundary of the
  # reflected process, so one lower-boundary routine serves both.
  f_lo <- .ddm_cdf_lower(t_adj, params$mu, params$boundary, params$bias)
  f_up <- .ddm_cdf_lower(t_adj, -params$mu, params$boundary, 1 - params$bias)

  # The outlier component is a half Normal, and its 1 / K sums back to one over
  # the response options - so the marginal carries all of it and a single
  # defective CDF carries its share.
  g_out <- 2 * stats::pnorm(pmax(params$x, 0) / .POUTLIER_SCALE) - 1
  if (is.null(response)) {
    dec <- f_lo + f_up
  } else {
    dec <- ifelse(params$response == 1, f_up, f_lo)
    g_out <- g_out / 2
  }

  # The attainable mass, which is what the two tails have to add back up to.
  # Marginally that is one; for a defective CDF it is the probability of that
  # response, so `lower.tail = FALSE` gives the defective survival
  # `P(RT > q, choice = response)` rather than `1 - P(RT <= q, choice =
  # response)`. The latter is `P(RT > q OR choice != response)`, which is not a
  # quantity anyone asks for - at `q = Inf` it returned the probability of the
  # *other* response instead of zero. Same convention as `pcogmod_rdm()`.
  #
  # `.ddm_plower()` is the limit `.ddm_cdf_lower()` itself takes at infinite
  # time, so the total is built the same way as the two defective CDFs above.
  if (is.null(response)) {
    total <- 1
  } else {
    p_lo <- .ddm_plower(params$mu, params$boundary, params$bias)
    p_up <- .ddm_plower(-params$mu, params$boundary, 1 - params$bias)
    total <- params$poutlier / 2 +
      (1 - params$poutlier) * ifelse(params$response == 1, p_up, p_lo)
  }

  out <- params$poutlier * g_out + (1 - params$poutlier) * dec
  out <- pmin(pmax(out, 0), total)
  if (!lower.tail) out <- total - out
  if (log.p) log(out) else out
}


# Family ------------------------------------------------------------------

#' @rdname rcogmod_ddm
#' @param link_mu,link_boundary,link_bias Link functions for the drift rate, the
#'   boundary separation and the starting point. `mu` is the drift: `brms`
#'   requires the first distributional parameter of a custom family to be called
#'   `mu`.
#' @param link_sigmadrift,link_sigmabias,link_sigmandt Link functions for the
#'   between-trial variability parameters. Fix them in the `brms::bf()` formula
#'   (e.g. `sigmadrift = 0`) to recover the classic 4-parameter DDM.
#' @param link_ndt,link_poutlier Link functions for the non-decision time and
#'   the outlier rate.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the diffusion alone; the likelihood is always the full mixture either way.
#'   On the prediction methods themselves the default is `NULL`, which defers to
#'   the flag carried on the model - see [with_outliers()]. See Details.
#' @export
cogmod_ddm <- function(
  link_mu = "identity",
  link_boundary = "softplus",
  link_bias = "logit",
  link_sigmadrift = "softplus",
  link_sigmabias = "logit",
  link_sigmandt = "log",
  link_ndt = "log",
  link_poutlier = "logit",
  predict_outliers = FALSE
) {
  .choice_family(
    "cogmod_ddm",
    links = c(link_mu, link_boundary, link_bias, link_sigmadrift,
              link_sigmabias, link_sigmandt),
    predict_outliers = predict_outliers
  )
}


# Internals ---------------------------------------------------------------

# Internal helpers for the extended (7-parameter) DDM ------------------------

#' @keywords internal
#' @noRd
.cogmod_ddm_has_variability <- function(params) {
  any(params$sigmadrift != 0, na.rm = TRUE) ||
    any(params$sigmabias != 0, na.rm = TRUE) ||
    any(params$sigmandt != 0, na.rm = TRUE)
}

#' Draw per-trial DDM parameters from their between-trial distributions
#'
#' Between-trial variability is, by definition, a hierarchical draw: the drift
#' is Normal, the starting point Uniform and the non-decision time Uniform
#' across trials. Drawing them and then running the plain 4-parameter process
#' reproduces the 7-parameter model exactly, so no dedicated sampler is needed.
#'
#' The parameterization matches the Stan likelihood in [cogmod_ddm_stanvars()]:
#' `sw = sigmabias * min(2*bias, 2*(1-bias))` with the starting point centred
#' on `bias`, and `st0 = sigmandt` directly, with `ndt` the *lower bound* of
#' the non-decision time (not its midpoint).
#'
#' @keywords internal
#' @noRd
.cogmod_ddm_draw_trialwise <- function(params) {
  n <- params$n

  params$drift <- stats::rnorm(n, params$drift, params$sigmadrift)

  sw <- params$sigmabias * pmin(2 * params$bias, 2 * (1 - params$bias))
  params$bias <- stats::runif(n, params$bias - sw / 2, params$bias + sw / 2)

  st0 <- params$sigmandt
  params$ndt <- pmax(stats::runif(n, params$ndt, params$ndt + st0), 0)

  params
}


#' Gauss-Legendre nodes and weights on `[-1, 1]`
#'
#' Computed with the Golub-Welsch algorithm (eigendecomposition of the Jacobi
#' matrix), so that no additional dependency is needed.
#'
#' @keywords internal
#' @noRd
.gauss_legendre <- function(n) {
  i <- seq_len(n - 1)
  b <- i / sqrt(4 * i^2 - 1)
  j <- matrix(0, n, n)
  j[cbind(i, i + 1)] <- b
  j[cbind(i + 1, i)] <- b
  e <- eigen(j, symmetric = TRUE)
  list(nodes = rev(e$values), weights = rev(2 * e$vectors[1, ]^2))
}


#' DDM density with between-trial variability in drift rate
#'
#' Integrating the 4-parameter Wiener density over a Normal drift has a closed
#' form: the density with zero drift, times a correction factor. No numerical
#' integration is required, so this costs one [brms::dwiener()] call.
#'
#' @keywords internal
#' @noRd
.cogmod_ddm_density_sv <- function(x, drift, boundary, bias, ndt, response, sigmadrift, ...) {
  dt <- x - ndt
  out <- rep(0, length(dt))
  ok <- !is.na(dt) & dt > 0
  if (!any(ok)) {
    return(out)
  }

  # Density of the driftless process; the drift enters through the correction.
  out[ok] <- brms::dwiener(
    x = x[ok],
    alpha = boundary[ok],
    beta = bias[ok],
    delta = 0,
    resp = response[ok],
    tau = ndt[ok],
    ...
  )

  # The upper boundary is the lower one with the drift and start point flipped.
  v <- ifelse(response[ok] == 1, -drift[ok], drift[ok])
  w <- ifelse(response[ok] == 1, 1 - bias[ok], bias[ok])
  sv2 <- sigmadrift[ok]^2
  num <- -v^2 * dt[ok] - 2 * v * boundary[ok] * w + sv2 * boundary[ok]^2 * w^2

  out[ok] <- out[ok] * exp(num / (2 * (1 + sv2 * dt[ok]))) / sqrt(1 + sv2 * dt[ok])
  out
}


#' Full (7-parameter) DDM density
#'
#' Drift variability is handled analytically by `.cogmod_ddm_density_sv()`; the
#' starting point and non-decision time are integrated out by Gauss-Legendre
#' quadrature over their Uniform distributions. The non-decision time is
#' integrated only up to `x`, since later start times contribute nothing -
#' this keeps the integrand smooth and the quadrature accurate.
#'
#' Validated against the Stan likelihood in [cogmod_ddm_stanvars()]: the maximum
#' relative error is at machine precision when only drift and starting-point
#' variability are present, and below 1e-5 with all three.
#'
#' @param nodes Number of quadrature nodes per integrated dimension.
#' @keywords internal
#' @noRd
.cogmod_ddm_density_var <- function(params, nodes = 25, ...) {
  n <- length(params$x)
  rec <- function(v) rep_len(v, n)

  x <- rec(params$x)
  drift <- rec(params$drift)
  boundary <- rec(params$boundary)
  bias <- rec(params$bias)
  ndt <- rec(params$ndt)
  response <- rec(params$response)
  sigmadrift <- rec(params$sigmadrift)

  sw <- rec(params$sigmabias) * pmin(2 * bias, 2 * (1 - bias))
  st0 <- rec(params$sigmandt)

  # A degenerate "node" of weight 2 reproduces the point value once the 1/2
  # factor of the uniform average is applied.
  degenerate <- list(nodes = 0, weights = 2)
  quad <- .gauss_legendre(nodes)
  w_quad <- if (any(sw > 0)) quad else degenerate
  t_quad <- if (any(st0 > 0)) quad else degenerate

  span <- pmax(pmin(ndt + st0, x) - ndt, 0)
  scale <- ifelse(st0 > 0, span / (2 * st0), 1 / 2)

  out <- numeric(n)
  for (a in seq_along(w_quad$nodes)) {
    bias_a <- bias + (sw / 2) * w_quad$nodes[a]
    inner <- numeric(n)
    for (b in seq_along(t_quad$nodes)) {
      ndt_b <- ndt + (span / 2) * (t_quad$nodes[b] + 1)
      inner <- inner + t_quad$weights[b] *
        .cogmod_ddm_density_sv(x, drift, boundary, bias_a, ndt_b, response, sigmadrift, ...)
    }
    out <- out + (w_quad$weights[a] / 2) * inner * scale
  }
  out
}


#' Translate `cogmod`'s parameterization into `rtdists`' one
#'
#' Not used by the package itself - the 7-parameter model is implemented
#' natively - but kept as the reference mapping for cross-checking against
#' [rtdists::ddiffusion()]/[rtdists::rdiffusion()]. Note that `rtdists` takes
#' the starting point and its variability on the absolute (`a`-scaled) scale,
#' and treats `t0` as the *lower* bound of the non-decision time distribution.
#'
#' @keywords internal
#' @noRd
.cogmod_ddm_to_rtdists <- function(params) {
  sw <- params$sigmabias * pmin(2 * params$bias, 2 * (1 - params$bias))
  list(
    a = params$boundary,
    v = params$drift,
    t0 = params$ndt,
    z = params$bias * params$boundary,
    sv = params$sigmadrift,
    sz = sw * params$boundary,
    st0 = params$sigmandt
  )
}

# CODE to BENCHMARK the backends

# # Load required packages
# library(brms)
# library(microbenchmark)

# # Function to randomly generate parameters
# generate_random_params <- function() {
#   list(
#     boundary = runif(1, 0.5, 2),  # Boundary separation: [0.5, 2]
#     bias = runif(1, 0.3, 0.7), # Starting point bias: [0.3, 0.7]
#     drift = runif(1, -1, 1),      # Drift rate: [-1, 1]
#     ndt = runif(1, 0.1, 0.5)   # Non-decision time: [0.1, 0.5]
#   )
# }

# # Benchmark settings
# n <- 5000  # Number of trials for simulation
# x <- seq(0.05, 2.5, length.out = 1000)  # Reaction times for density computation
# resp <- sample(c(1, 2), size = length(x), replace = TRUE)  # Random responses

# # Function to set backend and run rwiener with random parameters
# benchmark_rwiener <- function(backend) {
#   options(wiener_backend = backend)
#   params <- generate_random_params()
#   rwiener(n, boundary = params$boundary, bias = params$bias, delta = params$drift, tau = params$ndt)
# }

# # Function to set backend and run dwiener with random parameters
# benchmark_dwiener <- function(backend) {
#   options(wiener_backend = backend)
#   params <- generate_random_params()
#   dwiener(x, boundary = params$boundary, bias = params$bias, delta = params$drift, tau = params$ndt, resp = resp)
# }

# # Benchmark rwiener for both backends
# rwiener_benchmark <- microbenchmark(
#   Rwiener = benchmark_rwiener("Rwiener"),
#   rtdists = benchmark_rwiener("rtdists"),
#   times = 100
# )
# print("rwiener Benchmark:")
# print(rwiener_benchmark)
# autoplot(rwiener_benchmark) + ggtitle("rwiener Benchmark")

# # Benchmark dwiener for both backends
# dwiener_benchmark <- microbenchmark(
#   Rwiener = benchmark_dwiener("Rwiener"),
#   rtdists = benchmark_dwiener("rtdists"),
#   times = 100
# )

# # Print results
# print("dwiener Benchmark:")
# print(dwiener_benchmark)
# autoplot(dwiener_benchmark) + ggtitle("dwiener Benchmark")


# The decision component, as the registry wants it ------------------------

# `brms::dwiener()` insists on a strictly positive non-decision time, but the
# density depends on `q` and `tau` only through `q - tau`, so evaluating it at
# `q = t + .DDM_TAU0`, `tau = .DDM_TAU0` gives the decision density at `t`
# exactly. The value is far below any RT resolution and cancels to the last bit
# at every magnitude the density is ever asked about, so it is a workaround for
# an argument check rather than an approximation.
#' @keywords internal
.DDM_TAU0 <- 1e-10


# Log-density of the diffusion finishing at decision time `t` (already net of
# the non-decision time) at the boundary named by `k`: 1 is upper, 0 lower.
#
# `.ldec_choice()` masks out `t <= 0` and restores the shape afterwards, so this
# only has to work elementwise.
#
# This still goes through `brms::dwiener()`, unlike the sampler above, and that
# is deliberate rather than unfinished. `dwiener()` is slow - 6 us per element
# vectorised, and 1210 us when `resp` varies - so the question is what it costs
# in practice, and the answer is: only `log_lik()`, and once. Fitting is Stan,
# not this; `posterior_predict()` reaches the RNG and never the density; and
# `posterior_epred()` uses a closed form. That leaves `log_lik()`, hence
# `loo()`, at 67 us per draw-observation against 18 for the LNR and 25 for the
# LBA - a factor of three or four, not the order of magnitude the sampler was
# out by, and paid once per model rather than on every prediction.
#
# Rewriting it would mean a hand-rolled Navarro-Fuss density plus the
# between-trial variability machinery on top, and it would put LOO and every
# model comparison downstream of new numerics. That is a bad trade for a couple
# of minutes of one-off work, so it stays.
#' @keywords internal
.ddm_ldens <- function(t, k, p) {
  tv <- as.vector(t)
  n <- length(tv)
  # `brms::dwiener()` returns `list()` rather than `numeric(0)` on empty input,
  # and that list then reaches the arithmetic in `.log_mix()`.
  if (n == 0) return(numeric(0))
  rec <- function(v) rep_len(as.vector(v), n)

  pars <- list(
    x = tv + .DDM_TAU0,
    drift = rec(p$mu),
    boundary = rec(p$boundary),
    bias = rec(p$bias),
    ndt = rep(.DDM_TAU0, n),
    response = rec(k),
    sigmadrift = rec(p$sigmadrift),
    sigmabias = rec(p$sigmabias),
    sigmandt = rec(p$sigmandt)
  )

  if (.cogmod_ddm_has_variability(pars)) {
    return(log(.cogmod_ddm_density_var(pars)))
  }
  brms::dwiener(
    x = pars$x, alpha = pars$boundary, beta = pars$bias, delta = pars$drift,
    resp = pars$response, tau = pars$ndt, log = TRUE
  )
}


# Vectorised first-passage sampler ----------------------------------------
#
# `brms::rwiener()` samples one parameter set per call, so `posterior_predict()`
# - which brms drives one observation at a time, with every posterior draw
# carrying its own parameters - pays the sampler's fixed setup cost once per
# draw. Measured, that setup was about 85% of the cost: rtdists' marginal cost
# per draw is 1.4 us against a 772 us fixed cost, and RWiener's sampler does not
# amortise at all (55-90 us per draw at any n).
#
# So the draws are taken by inverting the CDF instead, which vectorises across
# parameter sets because every step acts on the whole vector at once. Two things
# make it cheap enough to be worth it:
#
#  * The large-time series for the defective lower-boundary CDF splits into a
#    part that depends on t and a part that does not. The root-finder varies
#    only t, so the rest is built once and each evaluation is a single exp()
#    and a column sum.
#  * The density falls out of the same exp(), because C_k * R_k reduces to
#    k sin(k pi w) / 2. A Newton step therefore costs exactly what a bisection
#    step costs.
#
# Accurate to 1e-13 in log RT against a 60-step bisection, and the underlying
# CDF agrees with numerical integration to 1e-9 - where `rtdists::pdiffusion()`
# is out by up to 5e-4. About 6x faster than `brms::rwiener()` per draw.

# Terms are kept until the last one is below this at the earliest time evaluated.
.DDM_SERIES_TOL <- 1e-13
# The series length grows as 1/sqrt(t), so an extreme starting point makes it
# long. The cap trades accuracy for time only in that corner.
.DDM_SERIES_CAP <- 400L
# Newton passes before the stragglers are handed to bisection. Eight leaves
# ~0.6% of draws for the cleanup, which is where the total cost bottoms out:
# fewer passes and the cleanup dominates, more and the passes do.
.DDM_NEWTON <- 8L
.DDM_EPS_V <- 1e-8

# P(the lower boundary is hit first), for a process starting at z = w * a.
#' @keywords internal
.ddm_plower <- function(v, a, w) {
  out <- numeric(length(v))
  small <- abs(v) < .DDM_EPS_V
  # A driftless walk hits 0 first with probability (a - z) / a: the start point
  # divides the interval and nothing biases it either way.
  if (any(small)) out[small] <- 1 - w[small]
  g <- !small
  if (any(g)) {
    x <- -2 * v[g] * a[g]
    y <- x * w[g]
    # Both exponents share the sign of -v, so writing it this way keeps whichever
    # one could overflow out of the expression entirely.
    out[g] <- ifelse(x < 0, (exp(x) - exp(y)) / expm1(x),
                     (1 - exp(y - x)) / (1 - exp(-x)))
  }
  pmin(pmax(out, 0), 1)
}

# Below this the lower-boundary CDF is under about 1e-15, so it is taken as
# zero. It doubles as the lower end of the root-finder's bracket, which is what
# bounds the series length: the number of terms needed grows as 1 / sqrt(t).
#' @keywords internal
.ddm_tfloor <- function(a, w) (a * w)^2 / 69

#' @keywords internal
.ddm_nterms <- function(a, tmin) {
  k <- a * sqrt(-2 * log(.DDM_SERIES_TOL) / (pi^2 * pmax(tmin, 1e-12)))
  as.integer(min(.DDM_SERIES_CAP, max(4L, ceiling(max(k)))))
}

# The t-independent half of the series, as K x n matrices.
#
#   S(t) = P_lo - F_lo(t) = pref * sum_k C_k exp(-R_k t)
#   f(t) = -dS/dt         = pref * sum_k C_k R_k exp(-R_k t)
#
# The survival is the series itself, formed with no cancellation, where the CDF
# is a difference that saturates. That is why the inversion below solves for the
# survival: on the CDF side the gradient vanishes in the right tail and Newton
# stalls.
#' @keywords internal
.ddm_series <- function(v, a, w, K) {
  n <- length(v)
  kk <- matrix(seq_len(K), K, n)
  aa <- matrix(a, K, n, byrow = TRUE)
  ww <- matrix(w, K, n, byrow = TRUE)
  vv <- matrix(v, K, n, byrow = TRUE)
  kpa <- kk^2 * pi^2 / aa^2
  list(C = kk * sin(kk * pi * ww) / (vv^2 + kpa),
       R = vv^2 / 2 + kpa / 2,
       pref = (2 * pi / a^2) * exp(-v * a * w),
       K = K, n = n)
}

# Defective CDF of the lower boundary: P(absorbed at 0, by time t).
#
# The same series the sampler inverts, evaluated once instead of repeatedly.
# Accurate to about 1e-9 against numerical integration of the density, where
# `rtdists::pdiffusion()` is out by up to 5e-4 - which is the reason this exists
# rather than delegating: `.ddm_fpt_rng()` inverts it, so its error would end up
# in the draws.
#' @keywords internal
.ddm_cdf_lower <- function(t, v, a, w) {
  out <- numeric(length(t))
  if (!length(t)) return(out)
  plo <- .ddm_plower(v, a, w)
  # At infinite time the process has been absorbed with certainty, so the
  # defective CDF has reached the choice probability of its own boundary. The
  # series cannot reach it - every term is exp(-R t), so the survival there is
  # exactly zero rather than small - and it is taken from `.ddm_plower()`
  # instead. Without this the branch below leaves the pre-allocated zero, which
  # is the value at t = 0, not at t = Inf.
  absorbed <- is.infinite(t) & t > 0
  out[absorbed] <- plo[absorbed]
  # Below the floor the CDF is under about 1e-15, and the series would need a
  # prohibitive number of terms to say so. Returning zero there is both cheaper
  # and, to double precision, right.
  live <- is.finite(t) & t > .ddm_tfloor(a, w)
  if (!any(live)) return(out)
  tl <- t[live]
  pre <- .ddm_series(v[live], a[live], w[live], .ddm_nterms(max(a[live]), min(tl)))
  s <- pre$pref * .colSums(pre$C * exp(-pre$R * rep(tl, each = pre$K)),
                           pre$K, pre$n)
  out[live] <- pmin(pmax(plo[live] - s, 0), plo[live])
  out
}


# Draw first-passage times for a Wiener process with drift `v`, boundary
# separation `a` and relative start point `w`, one parameter set per draw.
# Returns response 1 for the upper boundary, matching brms::rwiener().
#' @keywords internal
.ddm_fpt_rng <- function(n, v, a, w) {
  if (n == 0) return(list(rt = numeric(0), response = numeric(0)))
  v <- rep_len(v, n); a <- rep_len(a, n); w <- rep_len(w, n)

  resp_lower <- stats::runif(n) < .ddm_plower(v, a, w)
  q <- stats::runif(n)
  # The upper boundary is the lower one of the reflected process, so flipping
  # those draws leaves a single lower-boundary problem to solve.
  vf <- ifelse(resp_lower, v, -v)
  wf <- ifelse(resp_lower, w, 1 - w)
  pf <- .ddm_plower(vf, a, wf)

  lo <- .ddm_tfloor(a, wf)
  pre <- .ddm_series(vf, a, wf, .ddm_nterms(max(a), min(lo)))
  C <- pre$C; R <- pre$R; pref <- pre$pref; K <- pre$K
  ltarget <- log1p(-q) + log(pf)

  ev <- function(x, idx = NULL) {
    if (is.null(idx)) {
      ce <- C * exp(-R * rep(exp(x), each = K))
      list(S = pref * .colSums(ce, K, n), f = pref * .colSums(ce * R, K, n))
    } else {
      m <- length(idx)
      Ri <- R[, idx, drop = FALSE]
      ce <- C[, idx, drop = FALSE] * exp(-Ri * rep(exp(x), each = K))
      list(S = pref[idx] * .colSums(ce, K, m),
           f = pref[idx] * .colSums(ce * Ri, K, m))
    }
  }

  llo <- log(lo)
  lhi <- rep(log(60), n)
  # A near-driftless process behind a wide boundary can finish well past 60 s,
  # so the upper end is pushed out until it really does bracket the root.
  for (i in 1:8) {
    short <- log(ev(lhi)$S) > ltarget
    if (!any(short, na.rm = TRUE)) break
    lhi <- ifelse(short, lhi + log(16), lhi)
  }

  # Start from the one-term inversion, exact in the tail where a single term
  # carries the series.
  x <- log(pmax((log(pref * C[1, ]) - ltarget) / R[1, ], 1e-10))
  x <- pmin(pmax(x, llo + 1e-9), lhi - 1e-9)

  conv <- rep(FALSE, n)
  for (i in seq_len(.DDM_NEWTON)) {
    sf <- ev(x)
    h <- log(sf$S) - ltarget          # > 0: too much mass left, so t is too small
    dx <- h * sf$S / pmax(sf$f * exp(x), 1e-300)
    llo <- ifelse(!conv & h > 0, x, llo)
    lhi <- ifelse(!conv & h <= 0, x, lhi)
    xn <- x + dx
    # A converged draw sits on the bracket edge its own last evaluation set, so
    # the out-of-bracket test fires on exactly the steps that are already right.
    # Those are taken; only genuinely wild ones fall back to the midpoint.
    tiny <- is.finite(dx) & abs(dx) < 1e-10
    x <- ifelse(conv, x,
                ifelse((!is.finite(xn) | xn <= llo | xn >= lhi) & !tiny,
                       (llo + lhi) / 2, xn))
    conv <- conv | tiny
  }

  # Whatever Newton has not settled is bisected. The bracket is valid by
  # construction, so this cannot fail to converge.
  bad <- which(!conv)
  if (length(bad)) {
    bl <- llo[bad]; bh <- lhi[bad]; tg <- ltarget[bad]
    for (i in 1:50) {
      mid <- (bl + bh) / 2
      up <- log(ev(mid, bad)$S) > tg
      bl <- ifelse(up, mid, bl)
      bh <- ifelse(up, bh, mid)
    }
    x[bad] <- (bl + bh) / 2
  }
  list(rt = exp(x), response = as.numeric(!resp_lower))
}


# Decision-component sampler. Between-trial variability needs no special
# sampler: it *is* a hierarchical draw, so the per-trial drift, starting point
# and non-decision time are drawn and the ordinary 4-parameter process is run on
# top. The shift the mixture applies is added by `.rchoice()`, so the process
# here starts at zero.
#' @keywords internal
.ddm_rng <- function(n, p) {
  pars <- list(
    n = n,
    drift = p$mu,
    boundary = p$boundary,
    bias = p$bias,
    # Zero rather than `.DDM_TAU0`, unlike the density: that placeholder exists
    # only to get past rwiener()'s and dwiener()'s rejection of a zero
    # non-decision time, and this sampler has no such check to appease. Starting
    # at zero also leaves `draw_trialwise()` drawing the st0 offset on its own
    # scale, which is what gets added back below.
    ndt = numeric(n),
    sigmadrift = p$sigmadrift,
    sigmabias = p$sigmabias,
    sigmandt = p$sigmandt
  )
  if (.cogmod_ddm_has_variability(pars)) {
    pars <- .cogmod_ddm_draw_trialwise(pars)
  }
  sim <- .ddm_fpt_rng(n, v = pars$drift, a = pars$boundary, w = pars$bias)
  # `pars$ndt` carries the between-trial st0 offset and nothing else - the
  # family's own `ndt` is added by `.rchoice()`. It is exactly zero unless
  # `sigmandt` is free, so this costs nothing in the common case.
  list(rt = sim$rt + pars$ndt, response = sim$response)
}


# Stanvars ----------------------------------------------------------------

# The Stan literal is generated from `.DDM_TAU0` rather than written out, so
# the two implementations cannot end up shifted by different amounts.
#' @keywords internal
.DDM_STAN_PRELUDE <- sprintf("
// The decision component: Stan's Wiener density at the decision time. `w` is
// the starting point of whichever boundary is being scored, so the caller flips
// both it and the drift for the lower one.
//
// The shift is applied by the mixture around this, so the diffusion's own
// non-decision time should be zero - but wiener_lpdf() rejects that outright,
// and the density depends on the time and the non-decision time only through
// their difference. So both are offset by the same %s, exactly as the R side
// offsets them (see .DDM_TAU0). It is a workaround for an argument check rather
// than an approximation: at that magnitude the offset cancels to the last bit.
//
// sigmabias is a fraction of the widest start-point range that keeps the start
// point inside the boundaries, so sw = sigmabias * fmin(2w, 2(1-w)) - which is
// the same number for w and 1 - w, as it must be. sigmandt is st0 itself, in
// the same unit as Y, with the shift as its lower bound.
//
// Performance note: Stan's own `sw == 0 && st0 == 0` fast path inside
// `wiener_lpdf()` still delegates to the newer 'wiener5' algorithm (which also
// handles sv analytically), a structurally different and empirically much
// costlier implementation than the classic 4-parameter `wiener_lpdf()`, even
// when sv = 0. So we short-circuit ourselves whenever sw and st0 both vanish:
// to the classic 4-parameter Navarro & Fuss density when sv is also 0 (the
// fastest path), or to the dedicated 5-parameter (sv-only) form otherwise,
// which is still much cheaper than the general 7-parameter form (the latter
// falls back to adaptive numerical quadrature whenever sw or st0 is nonzero).
//
// The classic form is not usable everywhere, though - see
// cogmod_ddm_log_density_scale() below for the two regions it has to be kept
// out of, and why keeping it out of them is what removes the \"Non-finite
// gradient\" reports.

// A cheap estimate of the log first-passage density, used only to *route*
// between Stan's implementations - never as the density itself. Both call
// sites below fall back to an implementation that computes the exact value, so
// this being off in either direction costs a little speed and nothing else.
//
// Stan's classic 4-parameter `wiener_lpdf()` returns -inf in two regions, and
// hands back NaN partial derivatives when it does. A NaN partial is not made
// harmless by the mixture weight on it being zero: reverse-mode multiplies the
// (zero) adjoint into the stored partial, and 0 * NaN is NaN, so a single such
// trial turns the gradient of the whole model to NaN. That is what \"Error
// evaluating model log probability: Non-finite gradient\" reports during a
// Pathfinder search, and it is also why such a fit collects divergent
// transitions - a proposal whose gradient is not finite is rejected as one.
//
// The first region is the density underflowing to zero, which this function
// detects: the two series Navarro & Fuss give for the driftless, unit-boundary
// density at rescaled time tau = t / boundary^2 are each exact in their own
// tail and a wild extrapolation outside it, so the smaller of the two leading
// terms is the one to believe. Integrating a normal drift out of the density
// is closed-form, so sv enters as a factor rather than as another series. The
// second region is the alternating small-time series losing its sum to
// cancellation while the density is still perfectly representable; that one
// depends on tau alone - not on the drift or the scale separately - and is
// tested for at the call site.
//
// The general 7-parameter density averages over a start point spread across
// sw and a non-decision time spread across st0, so what matters there is
// whether *any* point of those ranges has a representable density. Each term
// is therefore taken at whichever end of each range makes it largest, which
// reduces to the point value when both ranges vanish.
real cogmod_ddm_log_density_scale(real t, real v, real boundary, real w,
                                  real sv, real sw, real st0) {
  real w_lo = fmax(w - sw / 2, 1e-12);
  real w_hi = fmin(w + sw / 2, 1 - 1e-12);
  real t_lo = fmax(t - st0, 1e-12);
  real tau_hi = t / square(boundary);
  real tau_lo = t_lo / square(boundary);

  // The small-time term rises with the decision time and peaks at a start
  // point of sqrt(tau); the large-time term falls with the decision time and
  // peaks at the start point nearest the midpoint.
  real ws = fmin(fmax(sqrt(tau_hi), w_lo), w_hi);
  real small = log(ws) - square(ws) / (2 * tau_hi)
               - 0.5 * log(2 * pi() * tau_hi^3);
  real wl = fmin(fmax(0.5, w_lo), w_hi);
  real large = log(pi()) - square(pi()) * tau_lo / 2 + log(sin(pi() * wl));

  // The drift factor, which at sv = 0 is just exp(-v * boundary * w -
  // v^2 * t / 2). Dropping the -log(sqrt(1 + sv^2 t)) that goes with it only
  // makes the estimate larger, which is the harmless direction.
  real num = -square(v) * t_lo - 2 * v * boundary * (v > 0 ? w_lo : w_hi)
             + square(sv * boundary * w_hi);
  real drift = num / (2 * (1 + square(sv) * (num > 0 ? t_lo : t)));

  return -2 * log(boundary) + fmin(small, large) + drift;
}

real cogmod_ddm_decision_lpdf(real t, real v, real boundary, real w,
                              real sigmadrift, real sigmabias, real sigmandt) {
  real tau0 = %s;
  // Below the offset the Wiener density has underflowed to zero anyway, so
  // -inf is the answer to double precision as well as the safe one.
  if (t <= tau0) return negative_infinity();
  real y = t + tau0;
  real sw = sigmabias * fmin(2 * w, 2 * (1 - w));

  if (sw == 0 && sigmandt == 0) {
    // The classic density, but only where it is sound. Cancellation sets in
    // below tau = 6.6e-4 (measured over w from 1e-6 to 1 - 1e-6 and |v| up to
    // 15, and invariant in the boundary and the drift), so the test keeps a
    // factor of 15 clear of it; from tau = 0.002 upwards the classic and the
    // sv-capable implementations agree to 1e-13, so there is no step in the
    // density where the two paths meet. The second test stops about 100 log
    // units short of underflow - far more slack than the estimate's error.
    if (sigmadrift == 0 && t > 0.01 * square(boundary)
        && cogmod_ddm_log_density_scale(t, v, boundary, w, 0, 0, 0) > -600) {
      return wiener_lpdf(y | boundary, tau0, w, v);
    }
    // wiener5 works in log space throughout: it stays finite, with finite
    // gradients, down to log-densities of -1e7 and beyond, so it needs no
    // guard of its own.
    return wiener_lpdf(y | boundary, tau0, w, v, sigmadrift);
  }
  // The 7-parameter form has the same -inf-with-NaN-partials failure as the
  // classic one and no sounder implementation to fall back on, so the answer
  // here is the -inf it would have returned anyway - only as a constant, which
  // carries no partial derivatives to poison the gradient with.
  if (cogmod_ddm_log_density_scale(t, v, boundary, w, sigmadrift, sw,
                                   sigmandt) < -600) {
    return negative_infinity();
  }
  return wiener_lpdf(y | boundary, tau0, w, v, sigmadrift, sw, sigmandt);
}
",
  formatC(.DDM_TAU0, format = "g", digits = 17, width = 1),
  formatC(.DDM_TAU0, format = "g", digits = 17, width = 1)
)


#' @keywords internal
.cogmod_ddm_lpdf <- function() {
  .choice_lpdf("cogmod_ddm")
}


#' @rdname rcogmod_ddm
#' @examples
#' \donttest{
#' # Exposing the Stan function needs cmdstanr and a CmdStan toolchain,
#' # which live outside CRAN - see the package website to install them.
#' if (requireNamespace("cmdstanr", quietly = TRUE) &&
#'     !is.null(cmdstanr::cmdstan_version(error_on_NA = FALSE))) {
#'   lpdf <- cogmod_ddm_lpdf_expose()
#'   lpdf(
#'     Y = 0.5, mu = 0.5, boundary = 1, bias = 0.5, sigmadrift = 0,
#'     sigmabias = 0, sigmandt = 0, ndt = 0.2, poutlier = 0.02, dec = 1
#'   )
#' }
#' }
#'
#' @export
cogmod_ddm_lpdf_expose <- function() {
  .choice_expose("cogmod_ddm")
}


#' @rdname rcogmod_ddm
#' @export
cogmod_ddm_stanvars <- function() {
  brms::stanvar(
    scode = .cogmod_ddm_lpdf(),
    block = "functions"
  )
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_ddm
#' @inheritParams rcogmod_betagate
#' @export
log_lik_cogmod_ddm <- function(i, prep) {
  .log_lik_choice("cogmod_ddm", i, prep)
}


#' @rdname rcogmod_ddm
#' @inheritParams rcogmod_betagate
#' @importFrom brms get_dpar
#' @export
posterior_predict_cogmod_ddm <- function(i, prep, predict_outliers = NULL,
                                         ...) {
  .posterior_predict_choice("cogmod_ddm", i, prep, predict_outliers)
}


#' @rdname rcogmod_ddm
#' @inheritParams rcogmod_betagate
#' @export
posterior_epred_cogmod_ddm <- function(prep, predict_outliers = NULL) {
  mu <- brms::get_dpar(prep, "mu")
  boundary <- brms::get_dpar(prep, "boundary")
  bias <- brms::get_dpar(prep, "bias")
  ndt <- brms::get_dpar(prep, "ndt")
  sigmadrift <- brms::get_dpar(prep, "sigmadrift")
  sigmabias <- brms::get_dpar(prep, "sigmabias")
  sigmandt <- brms::get_dpar(prep, "sigmandt")

  # The closed form below is exact only for the classic 4-parameter DDM. There
  # is no simple one once the between-trial variability is switched on, so say
  # so rather than return an approximation silently. (`sigmandt` is the one
  # exception in principle - it shifts the mean by st0 / 2 - but the other two
  # do not, and warning about some of them and not others would be worse.)
  if (any(sigmadrift != 0) || any(sigmabias != 0) || any(sigmandt != 0)) {
    warning(
      "posterior_epred() for cogmod_ddm() uses a closed form that is exact ",
      "only for the classic 4-parameter DDM (sigmadrift = sigmabias = ",
      "sigmandt = 0). The between-trial variability parameters are non-zero ",
      "here, so these expected RTs are approximate. Use posterior_predict() ",
      "and summarise the draws for exact ones.",
      call. = FALSE
    )
  }

  # Unconditional mean first-passage time plus the non-decision time. Formula
  # adapted from https://doi.org/10.1016/j.jmp.2009.01.006, which takes the
  # starting point on the absolute scale: `bias` is a proportion of `boundary`,
  # so the quantity entering it is z = bias * boundary, not `bias` itself.
  z <- bias * boundary
  epred <- ndt - z / mu +
    boundary / mu * (exp(-2 * mu * z) - 1) / (exp(-2 * mu * boundary) - 1)

  # The expression has a removable singularity at mu = 0 (and loses precision to
  # cancellation near it). The limit is ndt + z * (boundary - z).
  near_zero <- abs(mu) < 1e-6
  if (any(near_zero)) {
    # `+ 0 * mu` recycles the limit to the shape of the draws x observations
    # matrix, whatever mix of scalar and matrix dpars was supplied.
    lim <- ndt + z * (boundary - z) + 0 * mu
    epred[near_zero] <- lim[near_zero]
  }

  if (!.predict_outliers(predict_outliers, prep)) {
    return(epred)
  }
  poutlier <- brms::get_dpar(prep, "poutlier")
  (1 - poutlier) * epred + poutlier * .mcontam()
}
