#' @title Shifted Log-Weibull Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted
#' Log-Weibull distribution. A Log-Weibull-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rcogmod_logweibull()`: Simulates random draws.
#' - `dcogmod_logweibull()`: Computes the density (likelihood).
#' - `cogmod_logweibull()`: Creates a `brms::custom_family()`.
#' - `cogmod_logweibull_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `log(RT - ndt)` follows a **Gumbel** distribution with location `mu` and scale
#' `sigma` - the log-Weibull. The mean decision time is `exp(mu) * gamma(1 - sigma)`,
#' which exists only for `sigma < 1`.
#'
#' `ndt` and `poutlier` mean exactly what they do in [cogmod_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rcogmod_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' the outlier component's scale is a constant rather than a `dpar`, and why
#' reaction times have to be in seconds.
#'
#' `posterior_epred()` returns `Inf` where `sigma >= 1`, because the mean does not
#' exist there. Note this mean is *not* `exp(mu + sigma * 0.5772)`, which is the
#' geometric mean (the exponential of `E[log(RT - ndt)]`) rather than `E[RT - ndt]`.
#'
#' @inheritParams rcogmod_lognormal
#' @inheritParams cogmod_lnr
#' @param mu Location of the Gumbel distribution on the log scale. Any real value.
#' @param sigma Scale of the Gumbel distribution on the log scale. Must be positive.
#'
#' @return `rcogmod_logweibull()` returns a numeric vector of `n` simulated
#'   reaction times, in seconds. `dcogmod_logweibull()` returns the density at
#'   each element of `x` - the log density if `log = TRUE` - recycled to the
#'   length of the longest argument. `cogmod_logweibull()` returns a
#'   `brms::custom_family` object, to put on a `brms::bf()` formula.
#'   `cogmod_logweibull_stanvars()` returns a `brms::stanvars` object holding
#'   the family's Stan `functions` block, to pass to `brms::brm()`, and
#'   `cogmod_logweibull_lpdf_expose()` compiles that Stan code and returns it
#'   as an R function, for checking the density outside of a model. The
#'   remaining functions are `brms` post-processing methods, called by `brms`
#'   rather than directly: `log_lik_cogmod_logweibull()` returns a numeric
#'   vector holding one log-likelihood value per posterior draw for
#'   observation `i`, and `posterior_predict_cogmod_logweibull()` a draws x 1
#'   matrix of reaction times simulated for observation `i`.
#'   `posterior_epred_cogmod_logweibull()` returns a draws x observations
#'   matrix of expected reaction times, with `Inf` wherever the mean does not
#'   exist.
#'
#' @examples
#' rts <- rcogmod_logweibull(1000, mu = -0.8, sigma = 0.3, ndt = 0.3, poutlier = 0.02)
#' hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_logweibull(0.1, ndt = 0.3, poutlier = 0.02)
#' dcogmod_logweibull(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rcogmod_logweibull <- function(n, mu = -0.8, sigma = 0.3, ndt = 0.2, poutlier = 0) {
  .rshifted("cogmod_logweibull", n = n, ndt = ndt, poutlier = poutlier,
               mu = mu, sigma = sigma)
}


#' @rdname rcogmod_logweibull
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
dcogmod_logweibull <- function(x, mu = -0.8, sigma = 0.3, ndt = 0.2, poutlier = 0,
                      log = FALSE) {
  .dshifted("cogmod_logweibull", x = x, ndt = ndt, poutlier = poutlier,
               log = log, mu = mu, sigma = sigma)
}


#' @rdname rcogmod_logweibull
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
cogmod_logweibull <- function(link_mu = "identity", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE) {
  .shifted_family("cogmod_logweibull", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers)
}


#' @keywords internal
.cogmod_logweibull_lpdf <- function() {
  .shifted_lpdf("cogmod_logweibull")
}


#' @rdname rcogmod_logweibull
#' @export
cogmod_logweibull_lpdf_expose <- function() {
  .shifted_expose("cogmod_logweibull")
}


#' @rdname rcogmod_logweibull
#' @export
cogmod_logweibull_stanvars <- function() {
  brms::stanvar(scode = .cogmod_logweibull_lpdf(), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_logweibull
#' @export
log_lik_cogmod_logweibull <- function(i, prep) {
  .log_lik_shifted("cogmod_logweibull", i, prep)
}


#' @rdname rcogmod_logweibull
#' @export
posterior_predict_cogmod_logweibull <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("cogmod_logweibull", i, prep, predict_outliers)
}


#' @rdname rcogmod_logweibull
#' @export
posterior_epred_cogmod_logweibull <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("cogmod_logweibull", prep, predict_outliers)
}
