#' @title Shifted Wald Model (Inverse Gaussian)
#'
#' @description
#' Density, distribution function, random generation, and `brms` custom family
#' for the Shifted Wald distribution, also known as the Shifted Inverse Gaussian.
#' A Wald-distributed decision time is shifted by a non-decision time `ndt`, and
#' a fixed proportion `poutlier` of responses is generated by an outlier process
#' instead of by the decision process. The drift rate can be fixed across trials
#' (the classic Wald) or drawn afresh on each one, with SD `sigmadrift`.
#'
#' Functions:
#' - `rcogmod_invgaussian()`: Simulates random draws.
#' - `dcogmod_invgaussian()`: Computes the density (likelihood).
#' - `pcogmod_invgaussian()`: Computes the cumulative distribution function (CDF).
#' - `cogmod_invgaussian()`: Creates a `brms::custom_family()`.
#' - `cogmod_invgaussian_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' The Wald distribution describes the time it takes for a Wiener diffusion
#' process starting at 0 to reach a threshold `boundary` > 0, given a positive drift
#' rate `drift` > 0. That time is then shifted by a non-decision time `ndt`.
#'
#' It is mathematically equivalent to shifting an Inverse Gaussian distribution
#' with mean `boundary / drift` and shape `boundary^2`. In the `brms` family the drift rate
#' is named `mu`, since `brms` requires a parameter of that name.
#'
#' `ndt` and `poutlier` mean exactly what they do in [cogmod_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rcogmod_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' the outlier component's scale is a constant rather than a `dpar`, and why
#' reaction times have to be in seconds.
#'
#' The Wald density vanishes at the shift with all derivatives, like the
#' LogNormal, so `ndt` is well behaved here and there is no unbounded-likelihood
#' boundary of the kind [cogmod_gamma()] and [cogmod_weibull()] have at shape `< 1`.
#'
#' The random generation algorithm is that of Michael, Schucany, and Haas
#' (1976), as used in the `statmod` package.
#'
#' # Across-trial drift variability
#'
#' `sigmadrift` is the between-trial SD of the drift rate. At `sigmadrift = 0`,
#' its default, every trial accumulates at the same rate and the model is the
#' classic Wald. Above zero, each trial draws its own drift from a
#' `Normal(mu, sigmadrift)` **truncated at zero**, which is what lets the model
#' produce the long right tails empirical RT distributions have, and is the
#' single-accumulator counterpart of what [cogmod_ddm()] calls `sigmadrift` and
#' [cogmod_lba1()] calls `sigma`. Marginalising over that draw is a Gaussian
#' integral, so the density stays closed form and costs two normal CDFs.
#'
#' The truncation matters. A single-boundary accumulator handed a negative drift
#' never terminates, so an untruncated Normal would leave the density defective:
#' it integrates to 0.99 at `mu = 3, boundary = 0.5, sigmadrift = 1.5`, and to
#' 0.69 at `mu = 0.5, boundary = 1, sigmadrift = 2`. [cogmod_ddm()] needs no
#' such truncation, a diffusion between two boundaries always absorbing at one
#' of them.
#'
#' In a formula, `sigmadrift = 0` **fixes** the parameter and gives the classic
#' Wald; leaving it out of `bf()` altogether *estimates* it, which is not the
#' same thing:
#'
#' ```r
#' # Classic Wald
#' brms::bf(rt ~ 1, boundary ~ 1, sigmadrift = 0, ndt ~ 1, poutlier ~ 1,
#'          family = cogmod_invgaussian())
#'
#' # With across-trial drift variability
#' brms::bf(rt ~ 1, boundary ~ 1, sigmadrift ~ 1, ndt ~ 1, poutlier ~ 1,
#'          family = cogmod_invgaussian())
#' ```
#'
#' Fixing it is the better default, for two reasons. `sigmadrift` and
#' `poutlier` both fatten the right tail and are only weakly distinguishable:
#' on 2000 simulated trials at `mu = 3, boundary = 0.5, sigmadrift = 0.8`,
#' estimating `sigmadrift` buys about 2 log-likelihood units over fixing it at
#' zero, and the outlier weight absorbs most of the difference. And scaling
#' `mu`, `boundary` and `sigmadrift` up by a common factor sends the Wald to
#' the reciprocal-normal (LATER) limit, where the within-trial noise stops
#' mattering and `RT = boundary / drift` exactly - so large values of all three
#' describe nearly the same distribution. [cogmod_priors()] gives `sigmadrift`
#' a deliberately informative prior to fence off both.
#'
#' One consequence is worth stating plainly: with `sigmadrift > 0` the density
#' decays as `t^-2`, because drifts arbitrarily close to zero take arbitrarily
#' long, so **the mean does not exist**. [posterior_epred()][brms::posterior_epred]
#' returns `Inf`, as it does for [cogmod_invgamma()] at `shape <= 1`. Use
#' [posterior_predict()][brms::posterior_predict] and summarise the draws with a
#' median or a quantile instead.
#'
#' @inheritParams rcogmod_lognormal
#' @inheritParams cogmod_lnr
#' @param drift Drift rate. Must be positive. Represents the average speed of
#'   evidence accumulation. Range: (0, Inf).
#' @param boundary Decision threshold (boundary separation). Must be positive.
#'   Represents the amount of evidence needed to make a decision.
#'   Range: (0, Inf).
#' @param sigmadrift Between-trial SD of the drift rate. Must be non-negative.
#'   The drift of each trial is drawn from a `Normal(drift, sigmadrift)`
#'   truncated at zero. Default `0`, which is the classic fixed-drift Wald.
#'   Range: \[0, Inf).
#'
#' @references
#' - Michael, J. R., Schucany, W. R., & Haas, R. W. (1976). Generating Random Variates Using
#'     Transformations with Multiple Roots. *The American Statistician*, *30*(2), 88-90. \doi{10.2307/2683801}
#' - Anders, R., Alario, F., & Van Maanen, L. (2016). The shifted Wald distribution for
#'     response time data analysis. *Psychological Methods*, *21*(3), 309-327. \doi{10.1037/met0000063}
#' - Matzke, D., & Wagenmakers, E. J. (2009). Psychological interpretation of the ex-Gaussian
#'     and shifted Wald parameters: A diffusion model analysis. *Psychonomic Bulletin & Review*,
#'     *16*(5), 798-817. \doi{10.3758/PBR.16.5.798}
#' - Folks, J. L., & Chhikara, R. S. (1978). The inverse Gaussian distribution and its
#'     statistical application-a review. *Journal of the Royal Statistical Society Series B:
#'     Statistical Methodology*, *40*(3), 263-275.
#' - Tillman, G., Van Zandt, T., & Logan, G. D. (2020). Sequential sampling models without
#'     random between-trial variability: The racing diffusion model of speeded decision making.
#'     *Psychonomic Bulletin & Review*, *27*(5), 911-936. \doi{10.3758/s13423-020-01719-6}
#'
#' @return `rcogmod_invgaussian()` returns a numeric vector of `n` simulated
#'   reaction times, in seconds. `dcogmod_invgaussian()` returns the density
#'   at each element of `x` - the log density if `log = TRUE` - recycled to
#'   the length of the longest argument. `pcogmod_invgaussian()` returns the
#'   cumulative probability at each element of `q`, honouring `lower.tail` and
#'   `log.p`. `cogmod_invgaussian()` returns a `brms::custom_family` object,
#'   to put on a `brms::bf()` formula. `cogmod_invgaussian_stanvars()` returns
#'   a `brms::stanvars` object holding the family's Stan `functions` block, to
#'   pass to `brms::brm()`, and `cogmod_invgaussian_lpdf_expose()` compiles
#'   that Stan code and returns it as an R function, for checking the density
#'   outside of a model. The remaining functions are `brms` post-processing
#'   methods, called by `brms` rather than directly:
#'   `log_lik_cogmod_invgaussian()` returns a numeric vector holding one
#'   log-likelihood value per posterior draw for observation `i`, and
#'   `posterior_predict_cogmod_invgaussian()` a draws x 1 matrix of reaction
#'   times simulated for observation `i`.
#'   `posterior_epred_cogmod_invgaussian()` returns a draws x observations
#'   matrix of expected reaction times, with `Inf` wherever the mean does not
#'   exist.
#'
#' @examples
#' # Simulate 1000 RTs with 2% outliers
#' rts <- rcogmod_invgaussian(1000, drift = 3, boundary = 0.5, ndt = 0.2, poutlier = 0.02)
#' hist(rts, breaks = 50, xlab = "RT (s)")
#'
#' # The same, with the drift varying across trials: a longer right tail
#' rts_sv <- rcogmod_invgaussian(1000, drift = 3, boundary = 0.5, ndt = 0.2,
#'                               sigmadrift = 1, poutlier = 0.02)
#' quantile(rts, c(0.5, 0.99))
#' quantile(rts_sv, c(0.5, 0.99))
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_invgaussian(0.1, ndt = 0.3, poutlier = 0.02)
#' dcogmod_invgaussian(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rcogmod_invgaussian <- function(n, drift = 3, boundary = 0.5, ndt = 0.2,
                            sigmadrift = 0, poutlier = 0) {
  .rshifted("cogmod_invgaussian", n = n, ndt = ndt, poutlier = poutlier,
               mu = drift, boundary = boundary,
               sigmadrift = sigmadrift)
}


#' @rdname rcogmod_invgaussian
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
dcogmod_invgaussian <- function(x, drift = 3, boundary = 0.5, ndt = 0.2,
                            sigmadrift = 0, poutlier = 0, log = FALSE) {
  .dshifted("cogmod_invgaussian", x = x, ndt = ndt, poutlier = poutlier,
               log = log, mu = drift, boundary = boundary,
               sigmadrift = sigmadrift)
}


#' @rdname rcogmod_invgaussian
#' @param q Vector of quantiles (observed reaction times).
#' @param lower.tail Logical; if TRUE (default), probabilities are `P[X <= x]`,
#'   otherwise `P[X > x]`.
#' @param log.p Logical; if TRUE, probabilities p are given as log(p).
#' @export
pcogmod_invgaussian <- function(q, drift = 3, boundary = 0.5, ndt = 0.2,
                            sigmadrift = 0, poutlier = 0, lower.tail = TRUE, log.p = FALSE) {
  params <- .prepare_shifted("cogmod_invgaussian", x = q, ndt = ndt,
                                poutlier = poutlier, mu = drift,
                                boundary = boundary, sigmadrift = sigmadrift)

  t <- params$x - params$ndt
  cdf_dec <- rep(NA_real_, params$ndraws)
  # `t <= 0` is NA for a missing quantile, which makes `any(calc)` below NA and
  # the `if()` on it throw - the same failure `.dens_mask()` fixes on the
  # density side. Missing entries are excluded from all three masks here and
  # left at the NA they came in as.
  cdf_dec[!is.na(t) & t <= 0] <- 0
  inf_idx <- !is.na(t) & is.infinite(t) & t > 0
  cdf_dec[inf_idx] <- 1

  calc <- !is.na(t) & t > 0 & !inf_idx
  if (any(calc)) {
    # Closed form at sigmadrift = 0, quadrature over the drift above it - see
    # .pwald_raw(), which is where the reason for the difference is written down.
    cdf_dec[calc] <- .pwald_raw(t[calc], params$mu[calc],
                                params$boundary[calc], params$sigmadrift[calc])
  }

  # Mixture CDF: the outlier component has support over the whole positive line
  cdf <- params$poutlier * .pcontam(params$x) +
    (1 - params$poutlier) * cdf_dec

  if (!lower.tail) cdf <- 1 - cdf
  if (log.p) cdf <- log(cdf)
  cdf
}


#' @rdname rcogmod_invgaussian
#' @param link_mu,link_boundary,link_sigmadrift,link_ndt,link_poutlier Link
#'   functions for the parameters. `mu` is the drift rate. `sigmadrift` is
#'   legitimately zero, which is the classic Wald, and is fixed there by writing
#'   `sigmadrift = 0` in the formula.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
cogmod_invgaussian <- function(link_mu = "softplus", link_boundary = "softplus",
                           link_sigmadrift = "softplus",
                           link_ndt = "log", link_poutlier = "logit",
                           predict_outliers = FALSE) {
  .shifted_family("cogmod_invgaussian",
                     links = c(link_mu, link_boundary, link_sigmadrift),
                     predict_outliers = predict_outliers)
}


#' @keywords internal
.cogmod_invgaussian_lpdf <- function() {
  .shifted_lpdf("cogmod_invgaussian")
}


#' @rdname rcogmod_invgaussian
#' @export
cogmod_invgaussian_lpdf_expose <- function() {
  .shifted_expose("cogmod_invgaussian")
}


#' @rdname rcogmod_invgaussian
#' @export
cogmod_invgaussian_stanvars <- function() {
  brms::stanvar(scode = .cogmod_invgaussian_lpdf(),
                block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_invgaussian
#' @export
log_lik_cogmod_invgaussian <- function(i, prep) {
  .log_lik_shifted("cogmod_invgaussian", i, prep)
}


#' @rdname rcogmod_invgaussian
#' @export
posterior_predict_cogmod_invgaussian <- function(i, prep, predict_outliers = NULL,
                                             ...) {
  .posterior_predict_shifted("cogmod_invgaussian", i, prep, predict_outliers)
}


#' @rdname rcogmod_invgaussian
#' @export
posterior_epred_cogmod_invgaussian <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("cogmod_invgaussian", prep, predict_outliers)
}
