#' @title Shifted Inverse Gamma Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted
#' Inverse Gamma distribution. A Inverse Gamma-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rcogmod_invgamma()`: Simulates random draws.
#' - `dcogmod_invgamma()`: Computes the density (likelihood).
#' - `cogmod_invgamma()`: Creates a `brms::custom_family()`.
#' - `cogmod_invgamma_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `mu` is the **shape** and `sigma` the **scale** of the inverse Gamma
#' decision time, whose mean is `sigma / (mu - 1)` and exists only for `mu > 1`.
#'
#' `ndt` and `poutlier` mean exactly what they do in [cogmod_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rcogmod_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' the outlier component's scale is a constant rather than a `dpar`, and why
#' reaction times have to be in seconds.
#'
#' `posterior_epred()` returns `Inf` where `mu <= 1`, because the inverse Gamma
#' has no mean there. The right tail is a power law, so this family is the one to
#' reach for when the slow tail is heavy; [cogmod_loggamma()] covers the same
#' territory continuously through negative `shape`.
#'
#' @inheritParams rcogmod_lognormal
#' @inheritParams cogmod_lnr
#' @param mu Shape of the inverse Gamma decision time. Must be positive.
#' @param sigma Scale of the inverse Gamma decision time. Must be positive.
#'
#' @return `rcogmod_invgamma()` returns a numeric vector of `n` simulated
#'   reaction times, in seconds. `dcogmod_invgamma()` returns the density at
#'   each element of `x` - the log density if `log = TRUE` - recycled to the
#'   length of the longest argument. `cogmod_invgamma()` returns a
#'   `brms::custom_family` object, to put on a `brms::bf()` formula.
#'   `cogmod_invgamma_stanvars()` returns a `brms::stanvars` object holding
#'   the family's Stan `functions` block, to pass to `brms::brm()`, and
#'   `cogmod_invgamma_lpdf_expose()` compiles that Stan code and returns it as
#'   an R function, for checking the density outside of a model. The remaining
#'   functions are `brms` post-processing methods, called by `brms` rather
#'   than directly: `log_lik_cogmod_invgamma()` returns a numeric vector
#'   holding one log-likelihood value per posterior draw for observation `i`,
#'   and `posterior_predict_cogmod_invgamma()` a draws x 1 matrix of reaction
#'   times simulated for observation `i`. `posterior_epred_cogmod_invgamma()`
#'   returns a draws x observations matrix of expected reaction times, with
#'   `Inf` wherever the mean does not exist.
#'
#' @examples
#' rts <- rcogmod_invgamma(1000, mu = 4, sigma = 1.5, ndt = 0.3, poutlier = 0.02)
#' hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_invgamma(0.1, ndt = 0.3, poutlier = 0.02)
#' dcogmod_invgamma(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rcogmod_invgamma <- function(n, mu = 4, sigma = 1.5, ndt = 0.2, poutlier = 0) {
  .rshifted("cogmod_invgamma", n = n, ndt = ndt, poutlier = poutlier,
               mu = mu, sigma = sigma)
}


#' @rdname rcogmod_invgamma
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
dcogmod_invgamma <- function(x, mu = 4, sigma = 1.5, ndt = 0.2, poutlier = 0,
                      log = FALSE) {
  .dshifted("cogmod_invgamma", x = x, ndt = ndt, poutlier = poutlier,
               log = log, mu = mu, sigma = sigma)
}


#' @rdname rcogmod_invgamma
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
cogmod_invgamma <- function(link_mu = "softplus", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE) {
  .shifted_family("cogmod_invgamma", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers)
}


#' @keywords internal
.cogmod_invgamma_lpdf <- function() {
  .shifted_lpdf("cogmod_invgamma")
}


#' @rdname rcogmod_invgamma
#' @export
cogmod_invgamma_lpdf_expose <- function() {
  .shifted_expose("cogmod_invgamma")
}


#' @rdname rcogmod_invgamma
#' @export
cogmod_invgamma_stanvars <- function() {
  brms::stanvar(scode = .cogmod_invgamma_lpdf(), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_invgamma
#' @export
log_lik_cogmod_invgamma <- function(i, prep) {
  .log_lik_shifted("cogmod_invgamma", i, prep)
}


#' @rdname rcogmod_invgamma
#' @export
posterior_predict_cogmod_invgamma <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("cogmod_invgamma", i, prep, predict_outliers)
}


#' @rdname rcogmod_invgamma
#' @export
posterior_epred_cogmod_invgamma <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("cogmod_invgamma", prep, predict_outliers)
}
